version: '2'

services: 
  app:
    image: chrisubuntu/ergasia:latest
    command: python -u app.py
    ports:
      - "5000:5000"
    links:
      - db
  db:
    image: mongo:latest
    hostname: test_mongodb
    container_name: test_mongodb
    environment:
      - MONGO_INITDB_DATABASE=programme_db
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
    ports:
      - 27017:27017
